cozzee/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landingpage.urls', namespace='landingpage')),
    path('',include('APPComment.urls', namespace='APPComment')),
    path('',include('menupage.urls', namespace='menupage')),
    path('feedback/',include('feedback.urls', namespace='feedback')),
]

landingpage/urls.py
from django.urls import path
from . import views

app_name = 'landingpage'

urlpatterns = [
  path('',views.index, name='index'),
  path('toko/<int:id>/',views.toko, name='toko'),
  path('tambahToko/',views.tambahToko, name='tambahToko'),
]

menupage/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from menupage import views
from menupage.views import TambahMenu, TampilanMenu

app_name = 'menupage'

urlpatterns = [
    path('tambah-menu/<int:id>/', views.TambahMenu, name="tambah_menu"),
    path('menu-page/<int:id>/', views.TampilanMenu, name='menu_page'),
    # path('hapusmenu-page/', views.HapusMenu)
]

menupage/models.py
from django.db import models

# Create your models here.
class buatMenu(models.Model):
    Nama_Menu = models.CharField(max_length = 30)
    Harga_Menu = models.CharField(max_length = 20)
    Masukkan_Foto_Menu = models.URLField()
    id_toko = models.IntegerField()

    # def __str__(self):
    #     return self.Nama_Menu

menupage/forms.py
from django import forms 
from .models import buatMenu 

class MenuForm(forms.Form):
    Nama_Menu = forms.CharField(max_length = 30, label = "Nama Menu")
    Harga_Menu = forms.CharField(max_length = 20, label = "Harga Menu")
    Masukkan_Foto_Menu = forms.URLField(label = "Masukkan URL Foto Menu")

menupage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import buatMenu
from .forms import MenuForm
from landingpage.models import TambahToko

# Create your views here.
def TampilanMenu(request, id):
    semua_menu = buatMenu.objects.filter(id_toko = id)
    context = {"menu" : semua_menu,
    'id':id,
    'toko' : TambahToko.objects.get(id = id),
    }
    return render (request, 'TampilanMenuPage.html', context)

def TambahMenu(request, id):
    if request.method == "GET":      #Tampilin form-nya
        form = MenuForm()
        sent_data = {"menu_form" : form,
        'id':id
        }
        # return HttpResponse("ga masuk")
        return render (request, 'TambahMenuPage.html', sent_data)
    else: 
        isi_form = MenuForm(data=request.POST)     #dict yg isinya data yg telah di submit 
        if isi_form.is_valid():
            new_nama_menu = request.POST["Nama_Menu"]
            new_harga_menu = request.POST["Harga_Menu"]
            new_foto_menu = request.POST["Masukkan_Foto_Menu"]
            
            new_menu = buatMenu(
                Nama_Menu = new_nama_menu,
                Harga_Menu = new_harga_menu,
                Masukkan_Foto_Menu = new_foto_menu,
                id_toko = id
            )
            new_menu.save()
            return TampilanMenu(request, id)
        else:
            return HttpResponse("NOT SAVED")

# def DetailMenu(request, menu_id):
#     nama_object = buatMenu.objects.get(id = menu_id)
#     isi_context = {"isinya" : nama_object}
#     return render (request, 'MenuDetail.html', isi_context)

# def HapusMenu(request):
#     hapus = buatMenu.objects.all()
#     for x in hapus:
#         x.delete()
#     all = buatMenu.objects.all()
#     arg = {
#         "menu" : all
#     }
#     return render(request, 'TampilanMenuPage.html', arg)


    
            

menupage/templates/TambahMenuPage.html
<!DOCTYPE html>
{% load static %}
<html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'js/bootstrap.js' %}">
<link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<head>
 <title>Tambah Menu Page</title>
</head>
<style>
    html{
        padding: 0;
        margin: 0;
    }
    textarea {
        width : 100%;
        background: #EFEDED;
        border: 1px solid #000000;
        box-sizing: border-box;
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }
    body {
        background-color:#EFE9DB;
        font-family: Quattrocento;
        margin-top: 2vw;
    }
    h1 {
        position: absolute;
        font-family: Quattrocento;
        font-style: normal;
        font-weight: normal;
        font-size: 5vw;
        color: #354449;
    }
    .line {
        position: absolute;
        width: 83vw;
        height: 3px;
        top: 9vw;
        background: #D09780;
    }
    .form{
        margin-top: 10vw;
    }
    button, input {
        width: 89%;
        padding: 0.5vw;
        margin: 1vw;
        margin-left: 1vw;
        background: #EFEDED;
        border: 1px solid #000000;
        box-sizing: border-box;
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);

    }
    #id_Masukkan_Foto_Menu{
        width: 80%;
    }
    label{
        padding: 0;
        margin: 0;
    }
    .tolong{
        text-align: right;
        margin-right: 2vw;
    }
    .save{
        border: 1px solid #000000;
        width: 10vw;
        text-align: center;
        font-size: 1.5vw;
        box-shadow: 0px 0px 0px rgba(0, 0, 0, 0.25);
        margin: 0;
        padding: 0;
    }
    .save:hover{
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }
    
</style>
<body>
    <div style="padding-left:5%;padding-right:5%;">
    <div class="container" >
    <h1>Tambah Menu</h1>
    <div class="row">
        <div class="line"></div>
        <div class="col-12 form">
            {% block content %}
            <form action= "{% url 'menupage:tambah_menu' id %}" method="POST" class="post-form">
                {% csrf_token %}
                {{ menu_form.as_table }}
                {% endblock %}
            <div class="tolong">
                <button type="Submit" class="save btn btn-default">Kirim</button>
                <a href="{% url 'menupage:menu_page' id %}" class="save btn btn-default">Kembali</a>
            </div>
            </form>
            </div>
        </div>
    </div>
</div>
</body>
</html>

menupage/templates/TampilanMenuPage.html
<!DOCTYPE html>
{% load static %}
<html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'js/bootstrap.js' %}">
<link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<head>
 <title>Menu Page</title>
</head>
<style>
    textarea {
        width : 100%;
        background: #EFEDED;
        border: 1px solid #000000;
        box-sizing: border-box;
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }
    body {
        background-color:#EFE9DB;
        font-family: Quattrocento;
        margin-top: 2vw;
    }
    h1 {
        position: absolute;
        font-family: Quattrocento;
        font-style: normal;
        font-weight: normal;
        font-size: 5vw;
        left: 12vw;
        color: #354449;
    }
    .line {
        position: absolute;
        width: 83vw;
        height: 3px;
        top: 9vw;
        left: 10vw;
        background: #D09780;
    }
    .tolong{
        text-align: right;
        right: 12vw;
        position: fixed;
        bottom: 3vw;
    }
    .save{
        border: 1px solid #000000;
        width: 10vw;
        text-align: center;
        font-size: 1.5vw;
        box-shadow: 0px 0px 0px rgba(0, 0, 0, 0.25);
        margin: 0;
        padding: 0;
    }
    .save:hover{
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }
    
</style>
<body>
    <div style="padding-left:5%;padding-right:5%;">
        <h1>Menu - {{ toko.nama }}</h1>
        <div class="line"></div>
    <div class="container" style="padding-top: 8vw;">
        <div class="row my-5">
            {% for ngambil in menu %}
            <div class = "col-sm d-flex align-items-center" style="flex-basis: 25%;">
                <div class="card" style="width: 15rem;">
                <img
                src= "{{ ngambil.Masukkan_Foto_Menu }}"
                class="card-img-top"
                alt="{{ ngambil.Nama_Menu }}"
                />
                    <div class="card-body">
                <p class="card-text">
                <p> {{ngambil.Nama_Menu}} </p>
                <p> {{ngambil.Harga_Menu}} </p>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
    <div class="tolong">
        <a href="{% url 'menupage:tambah_menu' id %}"><button class="save btn btn-default" type="submit">Tambah Menu</button></a>
        <a href="{% url 'landingpage:toko' id %}"><button class="save btn btn-default" type="submit">Kembali</button></a>
        <!-- <a href="/hapusmenu-page/"><button class="save btn btn-default" type="submit">Delete</button></a> -->
    </div>
</body>
</html>