APPComment/urls.py
from django.contrib import admin
from django.urls import path
from .views import inputKomen, deleteKomen, index

app_name = 'APPComment'

urlpatterns = [
    path('adminSite/', admin.site.urls),
    path('indexComment/<int:id>/', index, name="indexComment"),
    path('input/<int:id>/', inputKomen, name="inputKomen"),
    path('delete/', deleteKomen),
]

cozzee/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landingpage.urls', namespace='landingpage')),
    path('',include('APPComment.urls', namespace='APPComment')),
    path('',include('menupage.urls', namespace='menupage')),
    path('feedback/',include('feedback.urls', namespace='feedback')),
]

landingpage/urls.py
from django.urls import path
from . import views

app_name = 'landingpage'

urlpatterns = [
  path('',views.index, name='index'),
  path('toko/<int:id>/',views.toko, name='toko'),
  path('tambahToko/',views.tambahToko, name='tambahToko'),
]

menupage/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from menupage import views
from menupage.views import TambahMenu, TampilanMenu

app_name = 'menupage'

urlpatterns = [
    path('tambah-menu/<int:id>/', views.TambahMenu, name="tambah_menu"),
    path('menu-page/<int:id>/', views.TampilanMenu, name='menu_page'),
    # path('hapusmenu-page/', views.HapusMenu)
]

landingpage/models.py
from django.db import models

class TambahToko(models.Model):
    nama = models.CharField(max_length = 30)
    alamat = models.CharField(max_length = 100)
    jam_operasional = models.CharField(max_length = 50)
    nomor_telepon = models.CharField(max_length = 15)
    harga_per_orang = models.CharField(max_length = 20)
    fasilitas = models.TextField(max_length = 200)
    foto_url = models.URLField()

    def __str__(self):
        return self.nama

landingpage/forms.py
from django.forms import ModelForm
from .models import TambahToko

class TambahTokoForm(ModelForm):
    class Meta:
      model = TambahToko
      fields = '__all__'

landingpage/views.py
from django.shortcuts import render, redirect
from APPComment.models import simpanKomen
from .models import TambahToko
from .forms import TambahTokoForm

# Create your views here.

def index(request):
    context = {
        'kedai' : TambahToko.objects.all()
    }
    return render(request,'index.html', context)  

def toko(request, id, optional = None):
    kedai = TambahToko.objects.get(id = id)
    try:
        komen = simpanKomen.objects.filter(id_toko = id)
    except:
        komen = None

    if komen == None or optional == None:
        countRasa = 0
        countSuasana = 0
        countPelayanan = 0
        for x in komen:
            countRasa += x.fieldRatingR
            countSuasana += x.fieldRatingS
            countPelayanan += x.fieldRatingP
        banyakIsi = simpanKomen.objects.all().count()
        if banyakIsi != 0:
            rataRataTotal = (countRasa+ countSuasana+ countPelayanan)/3
            countRasa = round(countRasa/banyakIsi, 1)
            countSuasana = round(countSuasana/banyakIsi, 1)
            countPelayanan = round(countPelayanan/banyakIsi, 1)
            rataRataTotal = round(rataRataTotal/banyakIsi, 1)
            optional = {
                'countR' : 2*countRasa,
                'countS' : 2*countSuasana,
                'countP' : 2*countPelayanan,
                'rataTotal' : 2*rataRataTotal
            }
    
    return render(request,'toko.html', {'kedai' :kedai, 'komen' : komen, 'nilai': optional})


def tambahToko(request):
    form = TambahTokoForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('/')

    return render(request, 'tambahToko.html', {
    'form' : form
  })

landingpage/templates/index.html
{% extends "base.html" %} {% block content %}
{% load static %}

<div class="row my-5">
    {%for kedai in kedai %}
  <div class="col-sm d-flex justify-content-center py-2">
    <div class="card" style="width: 18rem;">
      <a href="{% url 'landingpage:toko' id=kedai.id %}"
        ><img
          src="{{ kedai.foto_url }}"
          class="card-img-top"
          alt="Telegram Coffee"
          style="height: 200px;"
      /></a>
      <div class="card-body">
        <p class="card-text">
          {{kedai.nama}}
        </p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

landingpage/templates/tambahToko.html
{% extends "base.html" %} {% block content %}
{% load static %}

<form action="" method="POST">
<table>
        {% csrf_token %}
    {{ form.as_table }}
</table>
<input type="submit" value="Submit" style="margin: auto"/>
</form>
{% endblock %}

landingpage/templates/toko.html
{% extends "base.html" %} {% block content %}
{% load static %}

<div class="row my-4">
  <div class="col-md-6 d-flex justify-content-center align-items-center">
    <img
      src="{{ kedai.foto_url }}"
      class="card-img-top"
      alt="Telegram Coffee"
    />
  </div>
  <div class="col-md-6">
    <div class="row">
      <div class="col-sm" style="border-bottom: #D09780 2px solid; font-size: 2rem;">
        {{ kedai.nama }}
      </div>
    </div>
    {% if nilai == None %}
    <div class="row d-flex justify-content-around">
      <div class="col-xs-3">
        <div class="card">
          <h1
            class="badge badge-custom"
            style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; font-size: 100%;"
          >
            Rasa
          </h1>
          <div class="card-body py-0 mt-n2">
            <p class="card-text text-center" style="font-size: 200%;">
              0.0
            </p>
          </div>
        </div>
      </div>
      <div class="col-xs-3">
            <div class="card">
                    <h1
                      class="badge badge-custom"
                      style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; font-size: 100%;"
                    >
                      Suasana
                    </h1>
                    <div class="card-body py-0 mt-n2">
                      <p class="card-text text-center" style="font-size: 200%;">
                        0.0
                      </p>
                    </div>
                  </div>
      </div>
      <div class="col-xs-3">
            <div class="card">
                    <h1
                      class="badge badge-custom"
                      style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; font-size: 100%;"
                    >
                      Pelayanan
                    </h1>
                    <div class="card-body py-0 mt-n2">
                      <p class="card-text text-center" style="font-size: 200%;">
                        0.0
                      </p>
                    </div>
                  </div>
      </div>
      <div class="col-xs-3">
            <div class="card">
                    <h1
                      class="badge badge-custom"
                      style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; font-size: 100%;"
                    >
                      Total
                    </h1>
                    <div class="card-body py-0 mt-n2">
                      <p class="card-text text-center" style="font-size: 200%;">
                        0.0
                      </p>
                    </div>
                  </div>
      </div>
    </div>
    {% endif %}
    {% if nilai != none %}
    <div class="row d-flex justify-content-around">
        <div class="col-xs-3">
          <div class="card">
            <h1
              class="badge badge-custom"
              style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; font-size: 100%;"
            >
              Rasa
            </h1>
            <div class="card-body py-0 mt-n2">
              <p class="card-text text-center" style="font-size: 200%;">
                {{nilai.countR}}
              </p>
            </div>
          </div>
        </div>
        <div class="col-xs-3">
              <div class="card">
                      <h1
                        class="badge badge-custom"
                        style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; font-size: 100%;"
                      >
                        Suasana
                      </h1>
                      <div class="card-body py-0 mt-n2">
                        <p class="card-text text-center" style="font-size: 200%;">
                {{nilai.countS}}
                          
                        </p>
                      </div>
                    </div>
        </div>
        <div class="col-xs-3">
              <div class="card">
                      <h1
                        class="badge badge-custom"
                        style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; font-size: 100%;"
                      >
                        Pelayanan
                      </h1>
                      <div class="card-body py-0 mt-n2">
                        <p class="card-text text-center" style="font-size: 200%;">
                {{nilai.countP}}
                          
                        </p>
                      </div>
                    </div>
        </div>
        <div class="col-xs-3">
              <div class="card">
                      <h1
                        class="badge badge-custom"
                        style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; font-size: 100%;"
                      >
                        Total
                      </h1>
                      <div class="card-body py-0 mt-n2">
                        <p class="card-text text-center" style="font-size: 200%;">
                {{nilai.rataTotal}}
                        </p>
                      </div>
                    </div>
        </div>
      </div>
    {% endif %}
    <div class="row">
        <div class="col-xs-1 px-1">
            <i class="fas fa-map-marker-alt"></i>
        </div>
        <div class="col-xs-11">
            <p>&nbsp; {{ kedai.alamat }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-1 px-1">
            <i class="far fa-clock"></i>
        </div>
        <div class="col-xs-11">
            <p>{{ kedai.jam_operasional }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-1 px-1">
            <i class="fas fa-phone"></i>
        </div>
        <div class="col-xs-11">
            <p>{{ kedai.nomor_telepon }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-1 px-1">
            <i class="fas fa-coins"></i>
        </div>
        <div class="col-xs-11">
            <p>{{ kedai.harga_per_orang }}</p>
        </div>        
    </div>
    <div class="row pos px-1">
        {{ kedai.fasilitas }}
    </div>
    <div class="row">
        <div class="col-sm cui">
            <div style = "margin-top: 3vw;"></div>
            <a href="{% url 'APPComment:indexComment' kedai.id %}"><button class="save btn btn-default pos">Tulis Komentar</button>
            <a href="{% url 'menupage:menu_page' kedai.id %}"><button class="save btn btn-default pos">Lihat Menu</button></a>
        </div>
    </div>
  </div>
</div>

<div class="body">
    <div class='container-fluid row' id='bgform'>
        {% for x in komen %}
        <div class="col-md-2">
            <img src="{% static 'images/fotoKomen.png' %}" alt="" class="foto">
        </div>
        <div class="glyphicon glyphicon-triangle-left"></div>
        <div class='col-md-9' id='kotakagenda'>
            <h3 id="namakegiatan">{{x.fieldJudulKomen}}</h3>
            <hr>
            <h5 class="isiK">{{x.fieldIsiKomen}}</h5>
            <hr>
            <ul class="list-inline">
                <li class="list-inline-item"><h5 class="rating">Rating Rasa            :{{x.fieldRatingR}}</h5></li>
                <li class="list-inline-item"><h5 class="rating">Rating Rasa            :{{x.fieldRatingS}}</h5></li>
                <li class="list-inline-item"><h5 class="rating">Rating Rasa            :{{x.fieldRatingP}}</h5></li>
            </ul>
        </div>
    {% endfor %}   
    </div>
    <div class="container-fluid tombol">
        <!-- <a href="/delete/"><button class="btn btn-danger" type="submit">Delete</button></a> -->
    </div>
    
</div>
{% endblock %}