APPComment/urls.py
from django.contrib import admin
from django.urls import path
from .views import inputKomen, deleteKomen, index

app_name = 'APPComment'

urlpatterns = [
    path('adminSite/', admin.site.urls),
    path('indexComment/<int:id>/', index, name="indexComment"),
    path('input/<int:id>/', inputKomen, name="inputKomen"),
    path('delete/', deleteKomen),
]

cozzee/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landingpage.urls', namespace='landingpage')),
    path('',include('APPComment.urls', namespace='APPComment')),
    path('',include('menupage.urls', namespace='menupage')),
    path('feedback/',include('feedback.urls', namespace='feedback')),
]

landingpage/urls.py
from django.urls import path
from . import views

app_name = 'landingpage'

urlpatterns = [
  path('',views.index, name='index'),
  path('toko/<int:id>/',views.toko, name='toko'),
  path('tambahToko/',views.tambahToko, name='tambahToko'),
]

APPComment/models.py
from django.db import models

class simpanKomen(models.Model):
    fieldJudulKomen = models.CharField(max_length = 20, default = " ")
    fieldIsiKomen = models.CharField(max_length = 50, default = " ")
    fieldRatingR = models.IntegerField(default = 0)
    fieldRatingS = models.IntegerField(default = 0)
    fieldRatingP = models.IntegerField(default = 0)
    id_toko = models.IntegerField()

    # def __str__(self):
    #     return self.fieldJudulKomen

APPComment/forms.py
from django import forms

RATING_CHOICES = [
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
]

class formKomen(forms.Form):
    fieldJudulKomen = forms.CharField(label = 'Judul Komentar')
    fieldIsiKomen = forms.CharField(label = 'Komentar',widget=forms.Textarea(attrs={'rows': 10, 'cols': 15}))
    fieldRatingR = forms.ChoiceField(
        choices=RATING_CHOICES,
        label='Rating Rasa',
        # widget=forms.Select(attrs={'class':'col-md-4'}),
    )
    fieldRatingS = forms.ChoiceField(
        choices=RATING_CHOICES,
        label='Rating Suasana',
        # widget=forms.Select(attrs={'class':'col-md-4'}),
    )
    fieldRatingP = forms.ChoiceField(
        choices=RATING_CHOICES,
        label='Rating Pelayanan',
        # widget=forms.Select(attrs={'class':'col-md-4'}),
    )

APPComment/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import formKomen
from .models import simpanKomen
from landingpage.views import toko

def index(request, id):
    formulir = formKomen()
    argument = {
        'generated_html' : formulir,
        'id' : id
    }
    return render(request, 'input.html', argument)

def inputKomen(request, id):
    a = request.POST['fieldJudulKomen']
    b = request.POST['fieldIsiKomen']
    c = request.POST['fieldRatingR']
    d = request.POST['fieldRatingS']
    e = request.POST['fieldRatingP']
    f = id

    Komen = simpanKomen(
        fieldJudulKomen = a,
        fieldIsiKomen = b,
        fieldRatingR = c,
        fieldRatingS = d,
        fieldRatingP = e,
        id_toko = f
    )
    Komen.save()
    countRasa = 0
    countSuasana = 0
    countPelayanan = 0
    komen = simpanKomen.objects.all()
    for x in komen:
        countRasa += x.fieldRatingR
        countSuasana += x.fieldRatingS
        countPelayanan += x.fieldRatingP
    banyakIsi = simpanKomen.objects.all().count()
    rataRataTotal = rataRata(countRasa, countSuasana, countPelayanan)
    countRasa = round(countRasa/banyakIsi, 1)
    countSuasana = round(countSuasana/banyakIsi, 1)
    countPelayanan = round(countPelayanan/banyakIsi, 1)
    rataRataTotal = round(rataRataTotal/banyakIsi, 1)
    argumen = {
        'countR' : 2*countRasa,
        'countS' : 2*countSuasana,
        'countP' : 2*countPelayanan,
        'rataTotal' : 2*rataRataTotal
    }
    return toko(request,id, argumen)

def deleteKomen(request):
    all = simpanKomen.objects.all()
    for x in all:
        x.delete()
    countRasa = 0
    countSuasana = 0
    countPelayanan = 0
    komen = simpanKomen.objects.all()
    for x in komen:
        countRasa += x.fieldRatingR
        countSuasana += x.fieldRatingS
        countPelayanan += x.fieldRatingP
    rataRataTotal = rataRata(countRasa, countSuasana, countPelayanan)
    argumen = {
        'countR' : countRasa,
        'countS' : countSuasana,
        'countP' : countPelayanan,
        'rataTotal' : rataRataTotal,
        'komen' : komen
    }
    return render(request, 'hasil.html', argumen)

def rataRata(ratingR, ratingS, ratingP):
    return (ratingP+ratingR+ratingS)/3

# def tigaRata(request):
#     countRasa = 0
#     countSuasana = 0
#     countPelayanan = 0
#     komen = simpanKomen.objects.all()
#     for x in komen:
#         countRasa += x.fieldRatingR
#         countSuasana += x.fieldRatingS
#         countPelayanan += x.fieldRatingP
#     banyakIsi = simpanKomen.objects.all().count()
#     rataRataTotal = rataRata(countRasa, countSuasana, countPelayanan)
#     countRasa = round(countRasa/banyakIsi, 2)
#     countSuasana = round(countSuasana/banyakIsi, 2)
#     countPelayanan = round(countPelayanan/banyakIsi, 2)
#     rataRataTotal = round(rataRataTotal/banyakIsi, 2)
#     argumen = {
#         'countR' : countRasa,
#         'countS' : countSuasana,
#         'countP' : countPelayanan,
#         'rataTotal' : rataRataTotal,
#         'komen' : komen
#     }
#     return render(request, 'hasil.html', argumen)


    

APPComment/templates/hasil.html
{% extends "toko.html" %}
{% block content %}
{% load static %}
    <div class="body">
        <div class='container-fluid row' id='bgform'>
            <h5>RASA: {{countR}}</h5>
            <h5>SUASANA: {{countS}}</h5>
            <h5>PELAYANAN: {{countP}}</h5>
            <h5>RATA-RATA: {{rataTotal}}</h5>
            {% for x in komen %}
            <div class="col-md-2">
                <img src="{% static 'images/fotoKomen.png' %}" alt="" class="foto">
            </div>
            <div class="glyphicon glyphicon-triangle-left"></div>
            <div class='col-md-9' id='kotakagenda'>
                <h3 id="namakegiatan">{{x.fieldJudulKomen}}</h3>
                <hr>
                <h5 class="isiK">{{x.fieldIsiKomen}}</h5>
                <hr>
                <ul class="list-inline">
                    <li class="list-inline-item"><h5 class="rating">Rating Rasa            :{{x.fieldRatingR}}</h5></li>
                    <li class="list-inline-item"><h5 class="rating">Rating Rasa            :{{x.fieldRatingS}}</h5></li>
                    <li class="list-inline-item"><h5 class="rating">Rating Rasa            :{{x.fieldRatingP}}</h5></li>
                </ul>
            </div>
        {% endfor %}   
        </div>
        <div class="container-fluid tombol">
            <a href="/indexComment/"><button class="btn btn-danger" type="submit">Create</button></a>
            <a href="/delete/"><button class="btn btn-danger" type="submit">Delete</button></a>
        </div>
        
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    </div>

    {% endblock %}

APPComment/templates/input.html
<html>
{% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.js' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<head>
    <title>Kritik dan Saran</title>
</head>
<style>
    textarea {
        width : 100%;
        background: #EFEDED;
        border: 1px solid #000000;
        box-sizing: border-box;
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }
    body {
        background-color:#EFE9DB;
        font-family: Quattrocento;
        margin-top: 2vw;
    }
    h1 {
        position: absolute;
        left: 9vw;
        top: 3vw;
        font-family: Quattrocento;
        font-style: normal;
        font-weight: normal;
        font-size: 5vw;
        color: #354449;
    }
    .line {
        position: absolute;
        width: 90vw;
        height: 3px;
        left: 5vw;
        top: 9vw;
        background: #D09780;
    }
    .form{
        margin-top: 10vw;
    }
    button, input {
        width:69vw;
        background: #EFEDED;
        border: 1px solid #000000;
        box-sizing: border-box;
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
        margin-top: 1vw;
        margin-left: 1vw;
    }
    .tolong{
        /* padding-right: 5%; */
        text-align: right;
    }
    .save{
        border: 1px solid #000000;
        width: 7vw;
        text-align: center;
        font-size: 1.5vw;
        padding: 0;
    }
    select {
        word-wrap: normal;
        margin-top: 1vw;
        margin-left: 1vw;
        height: 2vw;
        width: 3vw;
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }
    #id_fieldIsiKomen {
        margin-top: 1vw;
        margin-left: 1vw;
        width: 69vw;
    }
    #id_fieldJudulKomen{
        height: 2.5vw;
    }
    th{
        text-align: left;
    }

    label {
        display: inline-block;
        margin-bottom: .5rem;
        margin-top: 1vw;
    }
    .btn:hover{
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }
    .inputBT{
        margin: 0;
        box-shadow: 0px 0px 0px rgba(0, 0, 0, 0.25);
    }
    /* .nyamping{
        padding-top: 10vw;
    }     */



</style>
<body>
    <div style="padding-left:5%;padding-right:5%;">
    <div class="container" >
        <h1>Tulis Komentar</h1>
        <div class="row">
            <div class="line"></div>
            <div class="col-12 form">
                {% block content %}
                <form method="POST" class="post-form" action="{% url 'APPComment:inputKomen' id %}">
                    {% csrf_token %}
                    <table>
                        <div class="row">
                                {{generated_html.as_table}}                        
                        </div>
                    </table>
                    <div class="tolong">
                        <input type="submit" value="Tambah" name="tombol" class="inputBT save btn btn-default">
                        <a class="save btn btn-default" href="{% url 'landingpage:toko' id %}">Kembali</a>
                    </div>
                </form>
                {% endblock %}
            </div>
        </div>
    </div>
</div>
</body>
</html>