cozzee/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landingpage.urls', namespace='landingpage')),
    path('',include('APPComment.urls', namespace='APPComment')),
    path('',include('menupage.urls', namespace='menupage')),
    path('feedback/',include('feedback.urls', namespace='feedback')),
]

feedback/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'feedback'

urlpatterns = [
    path('', views.feedback, name="feedback"),
]

landingpage/urls.py
from django.urls import path
from . import views

app_name = 'landingpage'

urlpatterns = [
  path('',views.index, name='index'),
  path('toko/<int:id>/',views.toko, name='toko'),
  path('tambahToko/',views.tambahToko, name='tambahToko'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0,shrink-to-fit=no"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <script src="https://kit.fontawesome.com/025b3a9369.js" crossorigin="anonymous"></script>
    <title>Cozzee</title>
  </head>
  <style>
      .pos{
        border: 2px solid #354449;
        box-sizing: border-box;
      }
      .cui{
          text-align: right;
      }
  </style>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-custom">
      <a class="navbar-brand" href="#"><img src="{% static 'images/LOGO.png' %}" style="width: 40%"></a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav d-flex justify-content-end w-100">
          <a class="nav-item nav-link" href="{% url 'landingpage:index' %}"
            >Beranda</a
          >
          <a class="nav-item nav-link" href="{% url 'landingpage:tambahToko' %}"
            >Tambah Kedai</a
          >
          <a class="nav-item nav-link" href="{% url 'feedback:feedback' %}">Kritik & Saran</a>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %} {% endblock %}
    </div>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>